### DISCUSSION TITLE
Differences between key and accessor

### DISCUSSION THREAD

**Discussion by ooker777** [RafaelGB/obsidian-db-folder#165] [Q&A] [answered]
From [About - Database Folder](https://rafaelgb.github.io/obsidian-db-folder/about/ "About - Database Folder"):

- key: name of obsidian field metadata in your notes (inline not supported edition yet)
- accessor: is the key of the data. Must be unique

For example:
```
columns:
  Calification:
    input: select
    accessor: Calification
    label: Calification
    key: Calification
```

I still don't know what is the difference between them. Are they the same? Can I use a field with multiple words without underscore in there?
