### DISCUSSION TITLE
Last row menu is hidden by "add button"

### DISCUSSION THREAD

**Discussion by imed-ghomari** [RafaelGB/obsidian-db-folder#427] [General]
### Contact Details

imeed166@gmail.com

### What happened?

The button should be beneath the last row, not above it.

https://user-images.githubusercontent.com/38974541/192090574-a80fe275-a5b2-43fd-97b0-ca7e8df1618c.mov

I'm using the theme from obsidian 0.15.9, If this is resolved with the new theme in 0.16, then ignore this issue

### What platform were you using?

Desktop

### Version of the plugin

2.6.6

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
the position of the add row button will be always on the bottom left corner.

Any better design will be welcomed

**Reply by imed-ghomari** [reply]
**Another design proposal:** move the `add row button` to the top bar, as there is unused space between the filters and the pagination. Unless, of course, you had planned to use that space for something else.

![that](https://user-images.githubusercontent.com/38974541/193323737-cd1adc3c-7ab4-4e89-9820-224c05a8a3a8.png)

**Reply by RafaelGB** [reply]
I was just thinking of using this new space to enable/disable the new filter groups.

Just like this:
<img width="261" alt="Screenshot 2022-09-30 at 19 25 51" src="https://user-images.githubusercontent.com/11924043/193324315-07e0aad0-2ba7-40a3-8737-53b0b4827ac4.png">

**Reply by imed-ghomari** [reply]
Oh, okay, good idea. Never mind then.

**Comment by RafaelGB** [comment]
You can modify it with a css snippet

**Comment by RafaelGB** [comment]
This is the current css
```css
.database-plugin__add-row {
  color: var(--text-accent);
  align-items: center;
  cursor: pointer;
  z-index: 3;
  position: fixed;
  margin-top: 2.65rem;
  bottom: 0;
  background-color: var(--background-primary);
}
.database-plugin__add-row .svg-icon:hover {
  background-color: var(--background-secondary);
  color: var(--text-accent-hover);
  padding: 0.3rem;
}

.database-plugin__add-row-input {
  height: 30px;
  max-height: 30px;
  border: 0 !important;
}

.database-plugin__add-row-input:focus {
  outline: none;
  border: 0 !important;
  box-shadow: 0 0 0 0 !important;
}
```
