### DISCUSSION TITLE
Some custom CSS to make the table look nicer

### DISCUSSION THREAD

**Discussion by randomsnowflake** [RafaelGB/obsidian-db-folder#575] [Show and tell]
This custom CSS snippet makes the UI look nicer.

There are only small changes but they have a huge impact (for me). These are:

- Checkboxes look smaller and prettier when using the Minimal Theme
- text is aligned left 

I tested it with the darkmode versions of the Default, Things and Minimal theme.

## My Custom CSS
```css
input[type=checkbox]:checked:after{
    background-color: var(--form-background);
}

.database-plugin__text-align-center {
	justify-content:left;
}

.database-plugin__td {
	text-align:left !important;
	padding-left:  1em !important;
}

.database-plugin__checkbox input[type="checkbox"] {
	border: 0.05em solid currentColor
}
```
