### DISCUSSION TITLE
Formula javascript

### DISCUSSION THREAD

**Discussion by VociNur** [RafaelGB/obsidian-db-folder#784] [Q&A]
Hey, I can’t use javascript in formula,
I have a code in "/js/test.js"
``` 
function test(){
    return "test";
}
module.exports = test;
```
I’m using the formula
`${db.js.test()}`

So my filename seems good, in setting, I activated the JS, and select the folder "js" 
What is the problem ?

**Comment by RafaelGB** [comment]
It seems correct. You can check the console logs enabling them inside the developer settings section (warning level will be enough)

I will check it myself with the same example

**Comment by VociNur** [comment]
I enable all setting section, but I don’t know where the logs are
And during this time, I see something:

Settings in DB Folder are activated
![js-setting](https://user-images.githubusercontent.com/48628008/215322837-6c4b2839-9ab9-43d9-b29a-7ef7258f1be7.png)
![Screenshot 2023-01-29 122242](https://user-images.githubusercontent.com/48628008/215322832-2422a4a5-a12e-4bb4-b159-135fdcc67cf0.png)

But in setting table, it isn’t
![table-setting](https://user-images.githubusercontent.com/48628008/215322834-2e469746-f324-43ef-9569-988c5755fc48.png)

And if I active them, my table disapear
![table-setting-js-activated](https://user-images.githubusercontent.com/48628008/215322836-17bdb8c4-323a-40a7-b2ef-cf21cdec3192.png)

**Reply by RafaelGB** [reply]
you can see the logs with ctrl+shift+i


I will investigate your issue the afternoon

**Comment by RafaelGB** [comment]
A quick test seems to work

https://user-images.githubusercontent.com/11924043/215323856-fad7c123-7ec8-4958-ab06-8098dec3773e.mov

**Comment by VociNur** [comment]
Sorry for the wait !

https://user-images.githubusercontent.com/48628008/215326081-41a9ae80-addc-47db-9bfb-c62f80fad578.mp4

**Reply by RafaelGB** [reply]
which version are you using? 3.3.0?

the problem of your video was resolved (I hope) with the beta of  the last version. 

Try to restart the Obsidian app

**Comment by VociNur** [comment]
Versions:
Obsidian: 1.1.9
Dataview: 0.5.55
DB Folder: 3.3.0

**Reply by RafaelGB** [reply]
🤕 I will check more use cases then

about the formulas, could you share your db file?

**Comment by VociNur** [comment]
This ? If you want to go on Discord I can, like this I can show you directly something if you have a question
---

database-plugin: basic

---

```yaml:dbfolder
name: new database
description: new description
columns:
  __file__:
    key: __file__
    id: __file__
    input: markdown
    label: File
    accessorKey: __file__
    isMetadata: true
    skipPersist: false
    isDragDisabled: false
    csvCandidate: true
    position: 1
    isHidden: false
    sortIndex: 1
    isSorted: true
    isSortedDesc: false
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: true
      task_hide_completed: true
      footer_type: none
      persist_changes: false
  Date:
    input: calendar
    accessorKey: Date
    key: Date
    id: Date_appris
    label: Date appris
    position: 2
    skipPersist: false
    isHidden: false
    sortIndex: -1
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
      footer_type: none
      persist_changes: false
  Col1:
    input: checkbox
    accessorKey: Col1
    key: Col1
    id: 1st_rep
    label: 1st rep
    position: 3
    skipPersist: false
    isHidden: false
    sortIndex: -1
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
      footer_type: none
      persist_changes: false
  Col2:
    input: checkbox
    accessorKey: Col2
    key: Col2
    id: 2st
    label: 2st
    position: 4
    skipPersist: false
    isHidden: false
    sortIndex: -1
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
      footer_type: none
      persist_changes: false
  Col3:
    input: checkbox
    accessorKey: Col3
    key: Col3
    id: 3st
    label: 3st
    position: 5
    skipPersist: false
    isHidden: false
    sortIndex: -1
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
      footer_type: none
      persist_changes: false
  Col4:
    input: checkbox
    accessorKey: Col4
    key: Col4
    id: 4st
    label: 4st
    position: 6
    skipPersist: false
    isHidden: false
    sortIndex: -1
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
      footer_type: none
      persist_changes: false
  Next_rep:
    input: formula
    accessorKey: Next_rep
    key: Next_rep
    id: Next_rep
    label: Next rep
    position: 100
    skipPersist: false
    isHidden: false
    sortIndex: -1
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
      footer_type: none
      persist_changes: false
      formula_query: ${db.js.test()}
config:
  remove_field_when_delete_column: false
  cell_size: normal
  sticky_first_column: false
  group_folder_column: 
  remove_empty_folders: false
  automatically_group_files: false
  hoist_files_with_empty_attributes: true
  show_metadata_created: false
  show_metadata_modified: false
  show_metadata_tasks: false
  show_metadata_inlinks: false
  show_metadata_outlinks: false
  source_data: current_folder
  source_form_result: 
  source_destination_path: /
  row_templates_folder: /
  current_row_template: 
  pagination_size: 10
  font_size: 16
  enable_js_formulas: false
  formula_folder_path: js
  inline_default: false
  inline_new_position: last_field
  date_format: yyyy-MM-dd
  datetime_format: "yyyy-MM-dd HH:mm:ss"
  metadata_date_format: "yyyy-MM-dd HH:mm:ss"
  enable_footer: false
  implementation: default
filters:
  enabled: false
  conditions:
```
