### ISSUE TITLE
Can't populate Nested YAML

### ISSUE THREAD

**Issue by LynetteCullens** [RafaelGB/obsidian-db-folder#1068]
> First of all you're not supposed to have spaces in your properties' names
> 
> I tested it myself and created `test test` with value `test` ![image](https://private-user-images.githubusercontent.com/19376127/298390532-943e4abf-759f-43d4-8bd5-fe8a88788580.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzODA5ODMsIm5iZiI6MTcxMzM4MDY4MywicGF0aCI6Ii8xOTM3NjEyNy8yOTgzOTA1MzItOTQzZTRhYmYtNzU5Zi00M2Q0LThiZDUtZmU4YTg4Nzg4NTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE5MDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NGE2YjBkMTc0ODg3Y2FjYTYyMjZmM2ZlMjc5NjIwODM2OTdmYWI0Zjg0OGUyNzc1MmI4ZDdmOTRiOTgzODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FDRqZDtcHVZc8OOe3MhxcasRQmKzWh-gVSo2wEFqIDo)
> 
> In the DB plugin when adding existing properties i get following recommendations: ![image](https://private-user-images.githubusercontent.com/19376127/298390619-13768551-48b1-46c1-82aa-cb19f2933d6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzODA5ODMsIm5iZiI6MTcxMzM4MDY4MywicGF0aCI6Ii8xOTM3NjEyNy8yOTgzOTA2MTktMTM3Njg1NTEtNDhiMS00NmMxLTgyYWEtY2IxOWYyOTMzZDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE5MDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMTk4NzE1Zjk0NWQyMTZhYmY4NjMxZGQ0NDAzMzI3YTY1MWEwNTJmN2UxMzY1MmU0MDhjNDY0NGY1MzUzY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0B56_8xpjQIbmJRrhIEXaBHpy9MCm5R0XcV6De1gS64)
> 
> When choosing `test-test` the corresponding testvalue gets displayed correctly in the DB view `test test` however would not show anything. ![image](https://private-user-images.githubusercontent.com/19376127/298390845-402e2c02-0b3e-4402-9977-54f81a0037c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzODA5ODMsIm5iZiI6MTcxMzM4MDY4MywicGF0aCI6Ii8xOTM3NjEyNy8yOTgzOTA4NDUtNDAyZTJjMDItMGIzZS00NDAyLTk5NzctNTRmODFhMDAzN2MwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE5MDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNDRlNmEzOWVmY2E3NzViNjQ5Yjk3YmFkZjQwMzE5YmZmZjg5YWQ2ZTRhNDg5YzE1ZDNjM2IwNDVmYjdmMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._UvcolYTFDNRsBZVfiXxA2_14mLK2KXT-CoweWLYoCU)
> 
> So even with spaces it's working

How would I go about getting the plugin to read a "-' in the column ID? I'm not allowed to change the ID itself because a plugin is depending on that particular format.
Edit: Specifically the nested columns under the column with a "-" in the title.

_Originally posted by @LynetteCullens in https://github.com/RafaelGB/obsidian-db-folder/issues/1025#issuecomment-2062023378_
            
   **### The following does not work:**

- `['mathLink-blocks']MKS`
- `mathLink-blocks.MKS`
- `[mathLink-blocks]MKS`
- `['mathLink-blocks'].MKS`
- ``[`\"mathLink-blocks\"`]MKS``

The above are syntax from various plugins that uses dataview.

When using:  ``[\"mathLink-blocks\"]MKS``
I get:

          
```shell
<p>TypeError: e.trim is not a function
    at ol (plugin:dbfolder:208:4025)
    at zFr (plugin:dbfolder:485:61919)
    at bq (plugin:dbfolder:173:19608)
    at Nxe (plugin:dbfolder:175:44301)
    at Oxe (plugin:dbfolder:175:39992)
    at tQt (plugin:dbfolder:175:39915)
    at GR (plugin:dbfolder:175:39764)
    at z3 (plugin:dbfolder:175:36108)
    at Dxe (plugin:dbfolder:175:35054)
    at D4 (plugin:dbfolder:168:59003)
    at Immediate.w4 [as _onImmediate] (plugin:dbfolder:168:59403)
    at process.processImmediate (node:internal/timers:476:21)</p>
```

**Comment by LynetteCullens** [comment]
Update:
After using [\"mathLink-blocks\"]MKS, it reverted back automatically to mathLink-blocks.MKS.
I manually changed the configuration in markdown to 
```
 mathLink-blocks.MKS:
    input: text
    accessorKey: mathLink-blocks
    label: MKS
    position: 100
    skipPersist: false
    isHidden: false
    sortIndex: -1
    nestedKey: MKS
    key: mathLink-blocks
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
      footer_type: none
      persist_changes: false
``` 
**The above works**
**Adding a nested column using the modal produces this format:**
```
mathLink-blocks.FPS:
    input: text
    accessorKey: mathLink-blocks.FPS
    key: mathLink-blocks.FPS
    id: mathLink-blocks.FPS
    label: mathLink-blocks.FPS
    position: 100
    skipPersist: false
    isHidden: false
    sortIndex: -1
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
      footer_type: none
      persist_changes: false
``` 
Which does not work.
