### ISSUE TITLE
text not centered (beta)

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#215]
**Describe the bug**
The text of these properties `text/file/checkbox/date/time` is slightly to the top

**Expected behavior**
It should be centered like the older versions

**Screenshots**

https://user-images.githubusercontent.com/38974541/180303375-bead730a-09cf-455d-8757-51347679fa7a.mov

**Desktop (please complete the following information):**
 - macOS 12.3.1
 - Obsidian 0.15.6
 - DB folder 2.0.0-beta.2

**Comment by RafaelGB** [comment]
Already working on it, this problem was introduced with beta.2  as trade of select empty cells

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/220

Special thanks to @artisticat1 who found the trick!

```css
span.is-loaded {
  display: flex;
  align-items: center;
}
```

```css
span.text-align-right {
  display: flex;
  align-items: center;
  justify-content: flex-end;
}
```
