### ISSUE TITLE
LaTeX inline mode forced to display mode

### ISSUE THREAD

**Issue by lashoun** [RafaelGB/obsidian-db-folder#228]
**Describe the bug**
When DBFolder is enabled, all inline LaTeX syntax is converted to display syntax, e.g. `$x$` is displayed as if it was `$$x$$`.

**To Reproduce**

1. Enable DBFolder
2. Open a note containing LaTeX syntax

**Expected behavior**
Inline LaTeX should be displayed correctly, inline.

**Screenshots**
Expected display: ![actual display](https://i.imgur.com/2kb8B83.png)

Actual display with DBFolder enabled: ![actual display](https://i.imgur.com/dsEzR3S.png)

**Additional context**
I suspect there is a duplication of dollar signs `$` but I can't say more since I do not know how DBFolder works precisely.

**Comment by RafaelGB** [comment]
hmm, could you share the markdown? Its so strange

**Comment by Zilard0** [comment]
Greetings,

I do have the same issue.

Expected:
![image](https://user-images.githubusercontent.com/87578914/182011294-3261c132-bd4c-4b81-b8ba-0f471ba9c7cb.png)

Actual:
![image](https://user-images.githubusercontent.com/87578914/182011277-c26a60d2-f572-4edc-b8de-57b03402470a.png)


Here is the markdown version:
`* Quantum harmonic oscillator: Two objects connected by a spring
* system satisfies a wavefunction
* Solutions are oscillatory and depend on reduced mass ($\mu$) and force constant ($k$) 
* Solutions have several distinct parts: The hermite polynomials (Even/odd functions) are especially useful.

**Comment by RafaelGB** [comment]
thanks for the example. Will be added to the roadmap

**Comment by 12-VidE** [comment]
Same problem over here

**Comment by lashoun** [comment]
Sorry I did not see your quick answer. Thanks to Zilard0 for providing a markdown example.

**Comment by RafaelGB** [comment]
seeing the impact of this problem I will give it priority as soon as I finish https://github.com/RafaelGB/obsidian-db-folder/issues/227

**Comment by RafaelGB** [comment]
Fixed!
```css
span.is-loaded,
span.database-plugin__calendar,
div.database-plugin__checkbox {
  display: flex;
  align-items: center;
  justify-content: center;
}
```
Changed for
```css
.database-plugin__td span.is-loaded,
span.database-plugin__calendar,
div.database-plugin__checkbox {
  display: flex;
  align-items: center;
  justify-content: center;
}
```

To do not interfere with Obsidian rendering

This also fix https://github.com/RafaelGB/obsidian-db-folder/issues/231
