### ISSUE TITLE
Enabling plugin causes ALL images to be centered

### ISSUE THREAD

**Issue by luckman212** [RafaelGB/obsidian-db-folder#231]
I saw this plugin mentioned on @eleanorkonik's Obsidian Roundup and wanted to check it out. First thing I noticed was as soon as I enabled the plugin (all settings left at defaults) all of my images were now centered horizontally. I assume this is just a CSS specificity problem but I didn't spend too much time looking into it.

Maybe related to https://github.com/RafaelGB/obsidian-db-folder/issues/215 ?

- DB Folder 2.0.1
- Obsidian 0.15.9
- macOS 12.5

**Comment by RafaelGB** [comment]
Hi @luckman212 , thanks for the report.

Could you share a markdown sample? I will add the issue to the roadmap as a bug

we solve this type of incompatibilities with other parts of obsidian under this function
```ts
/**
 * Wrap the classname of css elements
 * @param className 
 * @returns 
 */
export function c(className: string): string {
    const wrappedClasses: string[] = [];
    className.split(' ').forEach((cls) => {
        wrappedClasses.push(`${DatabaseCore.FRONTMATTER_KEY}__${cls}`);
    });
    return wrappedClasses.join(' ');
}
```

Once located, it should be fixed quickly

**Comment by luckman212** [comment]
Hi @RafaelGB sure, here's an easy sample

```md
1. Foo
2. Bar
3. Baz  
   ![[Pasted image 20220730104002.png]]
```

with DB Folder enabled

<img width="536" alt="image" src="https://user-images.githubusercontent.com/1992842/181919389-b8c22565-4376-4a59-ba70-b16e2d6e669c.png">

without

<img width="536" alt="image" src="https://user-images.githubusercontent.com/1992842/181919460-f6cc6d6e-ad33-4f92-9c5d-857e715378b6.png">

**Comment by RafaelGB** [comment]
as a bug, will take precedence and will be included for the next version

**Comment by RafaelGB** [comment]
Fixed.

```css
span.is-loaded,
span.database-plugin__calendar,
div.database-plugin__checkbox {
  display: flex;
  align-items: center;
  justify-content: center;
}
```
Changed for
```css
.database-plugin__td span.is-loaded,
span.database-plugin__calendar,
div.database-plugin__checkbox {
  display: flex;
  align-items: center;
  justify-content: center;
}
```
