### ISSUE TITLE
[Bug]: last row menu is hidden by "add button"

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#423]
### Contact Details

imeed166@gmail.com

### What happened?

The button should be beneath the last row, not above it.

https://user-images.githubusercontent.com/38974541/192090574-a80fe275-a5b2-43fd-97b0-ca7e8df1618c.mov

I'm using the theme from obsidian 0.15.9, If this is resolved with the new theme in 0.16, then ignore this issue

### What platform were you using?

Desktop

### Version of the plugin

2.6.6

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
the position of the add row button will be always on the bottom left corner.

Any better design will be welcomed

**Comment by RafaelGB** [comment]
You can modify it with a css snippet

**Comment by RafaelGB** [comment]
This is the current css
```css
.database-plugin__add-row {
  color: var(--text-accent);
  align-items: center;
  cursor: pointer;
  z-index: 3;
  position: fixed;
  margin-top: 2.65rem;
  bottom: 0;
  background-color: var(--background-primary);
}
.database-plugin__add-row .svg-icon:hover {
  background-color: var(--background-secondary);
  color: var(--text-accent-hover);
  padding: 0.3rem;
}

.database-plugin__add-row-input {
  height: 30px;
  max-height: 30px;
  border: 0 !important;
}

.database-plugin__add-row-input:focus {
  outline: none;
  border: 0 !important;
  box-shadow: 0 0 0 0 !important;
}
```
