### ISSUE TITLE
[Bug]: top bar menus don't support dark mode

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#425]
### Contact Details

imeed166@gmail.com

### What happened?

I'm using the theme from obsidian 0.15.9, If this is resolved with the new theme in 0.16, then ignore this issue

![image](https://user-images.githubusercontent.com/38974541/192090415-cce96aed-01bd-421f-93fb-46348051878d.png)

### What platform were you using?

Desktop

### Version of the plugin

2.6.6

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Included on the roadmap

**Comment by RafaelGB** [comment]
The style of the buttons depends of the default theme

```css
button:not(.clickable-icon) {
    background-color: var(--interactive-normal);
    box-shadow: var(--input-shadow);
}
```
Personally I liked the style, but you can change it with a css snippet
