### ISSUE TITLE
[FR]: Column move line

### ISSUE THREAD

**Issue by DannyHatcher-Git** [RafaelGB/obsidian-db-folder#519]
### Contact Details

danny@dannyhatcher.com

### Present your request

When moving a column from left to right by dragging it, having a visible line as to where it will be dropped would be handy.

### For which platform do you request this request??

Desktop

**Comment by RafaelGB** [comment]
I am agree but its not trivial since the drag and drop method was realised from zero, so there is no logic for that yet

**Comment by DannyHatcher-Git** [comment]
ah ok. I will stick with the move left and right until then.

Could we hotkey those actions as commands?

**Comment by RafaelGB** [comment]
https://github.com/RafaelGB/obsidian-db-folder/issues/154

**Comment by RafaelGB** [comment]
```css
/*************************
*  Headers DnD styles
**************************/
.database-plugin__dnd-over {
  background-color: var(--background-secondary);
  box-shadow: rgba(14, 30, 37, 0.12) 0px 2px 4px 0px,
    rgba(14, 30, 37, 0.32) 0px 2px 16px 0px;
}

.database-plugin__dnd-dragging {
  opacity: 0.5;
  background-color: var(--background-modifier-box-shadow);
}
```

Customisable with a css snippet
