### ISSUE TITLE
[Bug]: DB Folder view crashes when using Icons as values

### ISSUE THREAD

**Issue by namtrah** [RafaelGB/obsidian-db-folder#615]
### Contact Details

GitHub User namtrah

### What happened?

I have in my frontmatter a field :
    `campaign-status: ":fas_heartbeat:"` 
which uses the Icons Plugin to show a :heartbeat: symbol. When trying to use this field in DBFolder, it crashes and doesn't show the DB. The error shown is in the error log:

### What platform were you using?

Desktop

### Version of the plugin

2.8.4

### Relevant log output

```shell
plugin:dbfolder:10 Uncaught (in promise) Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Error%5D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ga (plugin:dbfolder:10:55553)
    at e (plugin:dbfolder:10:60518)
    at bs (plugin:dbfolder:10:71780)
    at Cl (plugin:dbfolder:10:120549)
    at Du (plugin:dbfolder:10:107743)
    at gu (plugin:dbfolder:10:107671)
    at mu (plugin:dbfolder:10:107534)
    at su (plugin:dbfolder:10:104675)
    at Ho (plugin:dbfolder:10:46097)
    at uu (plugin:dbfolder:10:105179)
```

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
I will work on this issue. Thanks for the report @namtrah 💗

**Comment by RafaelGB** [comment]
I tested it and icons works perfectly

Could you share more details of your issue?

Operative system?

**Comment by namtrah** [comment]
I just tried by opening the sandbox and copying my party directory (only plugin installed was this one.)

OS: Ubuntu 22.04 LTS

I have reduced it to two files and to just the bare minimum of text. I can upload t
[Party DB.md](https://github.com/RafaelGB/obsidian-db-folder/files/10070873/Party.DB.md)
[Player.md](https://github.com/RafaelGB/obsidian-db-folder/files/10070874/Player.md)
hem here.

**Comment by namtrah** [comment]
Two comments. the above file "Player.md" doesn't even use :fas_heartbeat:, and the icons plugin wasn't even installed.
Second, after installing the icons plugin and enabling the Font Awesome Solid icons, I can use this, but it still breaks. 
I may also have had to add Icons Shortcodes Plugin to get the ":fas_heartbeat:" codelink.

Changing line `campaign-status: "👻" ` to campaign-status: ":fas_heartbeat:" didn't do much.

**Comment by RafaelGB** [comment]
In your sandbox the filters where not readable.

If you open the db as markdown you can see a value filter condition as `value: :fas_heartbeat:` .It can not be read by Obsidian yaml because it requires quotes. (some versions ago the plugin adds them automatically)

KO
```yaml
filters:
  enabled: true
  conditions:
      - field: type
        operator: EQUAL
        value: pc
      - field: campaign-status
        operator: EQUAL
        value: :fas_heartbeat:
```

OK
```yaml
filters:
  enabled: true
  conditions:
      - field: type
        operator: EQUAL
        value: pc
      - field: campaign-status
        operator: EQUAL
        value: "👻"
```
