### ISSUE TITLE
[Bug]: Multiple persistent formula values are not saved on refresh; only one of the persistent values is updated in the YAML frontmatter.

### ISSUE THREAD

**Issue by hrosenbrock** [RafaelGB/obsidian-db-folder#616]
### Contact Details

henry@rosenbrock.me

### What happened?

If a database has multiple formulas with persistent values, only one of them is saved to the YAML frontmatter.  It appears that the last column is saved, but I am not 100% confident that it is that value.   I am currently working around this issue in my database, with 2 persistent formula values, by disabling persistance on one then refreshing then re-enabling it.  This will save both values to the YAML frontmatter.

### What platform were you using?

Desktop

### Version of the plugin

2.8.4

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
There may be a race condition. They all save in the file but start from the same information and only the last one is persisted

I will investigate it. Thanks!

**Comment by hrosenbrock** [comment]
I created a simplified version of the database with just one 'Test' row.  I also added some debug code and enabled the INFO level debugging.  It appears the 'updateRowFile' is called twice, once for each persistent formula.  The first call is correct and produces the correct frontmatter, however the second call is missing the other formula value.  The log is below:

2022-11-22T03:07:28.531Z] [info] =>updateRowFile. file: ☑️ Task Management/Schedule/Test.md | columnId: start | newValue: 2022-11-15 | option: column_value
Logger.ts:71 [2022-11-22T03:07:28.532Z] [info] =>updateRowFile. file: ☑️ Task Management/Schedule/Test.md | columnId: finish | newValue: 2022-11-23 | option: column_value
EditEngineService.ts:144 persistFromtmatter: ---
start_date: 2022-11-15
finish_date: 2022-11-23
finish: 2022-11-23
start: 2022-11-15
---

EditEngineService.ts:144 persistFromtmatter: ---
start_date: 2022-11-15
finish_date: 2022-11-23
finish: 2022-11-23
---

Logger.ts:71 [2022-11-22T03:07:28.617Z] [info] <= updateRowFile.asociatedFilePathToCell: ☑️ Task Management/Schedule/Test.md | columnId: start | newValue: 2022-11-15 | option: column_value 
Logger.ts:71 [2022-11-22T03:07:28.619Z] [info] <= updateRowFile.asociatedFilePathToCell: ☑️ Task Management/Schedule/Test.md | columnId: finish | newValue: 2022-11-23 | option: column_value

**Comment by hrosenbrock** [comment]
I created a simplified version of the database which just has one row.  The database has 2 formulas simply copying the date from other fields.  I added some debugging statements to your code and you definitely have an evil race condition.

It looks like the 'app.vault.modify' is occurring after the both modification updates are completed.  Since the second update is using the data from the note, it is missing the first update and therefore overwriting the data.


```
[2022-11-22T03:32:55.834Z] [info] => editNoteContent. action:replace filePath:☑️ Task Management/Schedule/Schedule.md
plugin:dbfolder:50900 [2022-11-22T03:32:55.871Z] [info] =>updateRowFile. file: ☑️ Task Management/Schedule/Test.md | columnId: start | newValue: 2022-11-15 | option: column_value
plugin:dbfolder:50900 [2022-11-22T03:32:55.871Z] [info] =>updateRowFile. file: ☑️ Task Management/Schedule/Test.md | columnId: finish | newValue: 2022-11-23 | option: column_value
plugin:dbfolder:96753 original: ---
start_date: 2022-11-15
finish_date: 2022-11-23
---

plugin:dbfolder:96810 persistFromtmatter: ---
start_date: 2022-11-15
finish_date: 2022-11-23
start: 2022-11-15
---

plugin:dbfolder:50900 [2022-11-22T03:32:55.928Z] [info] => editNoteContent. action:replace filePath:☑️ Task Management/Schedule/Test.md
plugin:dbfolder:96753 original: ---
start_date: 2022-11-15
finish_date: 2022-11-23
---

plugin:dbfolder:96810 persistFromtmatter: ---
start_date: 2022-11-15
finish_date: 2022-11-23
finish: 2022-11-23
---

plugin:dbfolder:50900 [2022-11-22T03:32:55.931Z] [info] => editNoteContent. action:replace filePath:☑️ Task Management/Schedule/Test.md
plugin:dbfolder:50900 [2022-11-22T03:32:55.948Z] [info] <= editNoteContent. file '☑️ Task Management/Schedule/Schedule.md' edited
plugin:dbfolder:50900 [2022-11-22T03:32:55.961Z] [info] <= editNoteContent. file '☑️ Task Management/Schedule/Test.md' edited
plugin:dbfolder:50900 [2022-11-22T03:32:55.961Z] [info] => editNoteContent. action:replace filePath:☑️ Task Management/Schedule/Test.md
plugin:dbfolder:50900 [2022-11-22T03:32:55.974Z] [info] <= editNoteContent. file '☑️ Task Management/Schedule/Test.md' edited
plugin:dbfolder:50900 [2022-11-22T03:32:55.975Z] [info] => editNoteContent. action:replace filePath:☑️ Task Management/Schedule/Test.md
plugin:dbfolder:50900 [2022-11-22T03:32:55.993Z] [info] <= editNoteContent. file '☑️ Task Management/Schedule/Test.md' edited
plugin:dbfolder:50900 [2022-11-22T03:32:55.993Z] [info] <= updateRowFile.asociatedFilePathToCell: ☑️ Task Management/Schedule/Test.md | columnId: start | newValue: 2022-11-15 | option: column_value 
plugin:dbfolder:50900 [2022-11-22T03:32:55.995Z] [info] <= editNoteContent. file '☑️ Task Management/Schedule/Test.md' edited
plugin:dbfolder:50900 [2022-11-22T03:32:55.996Z] [info] <= updateRowFile.asociatedFilePathToCell: ☑️ Task Management/Schedule/Test.md | columnId: finish | newValue: 2022-11-23 | option: column_value 
```

**Comment by hrosenbrock** [comment]
It appears that you need to process all formula columns within a single update.  However, given how you have the FormulaCell setup I am not sure if it is possible to process all formula cells within the same 'useEffect' async block.

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/203257738-a12692ca-e120-4c41-b901-bf199e8d5615.mov

Fixed with a cool solution

Commit 50c0a7d0

**Comment by RafaelGB** [comment]
https://user-images.githubusercontent.com/11924043/203311443-13eb00d7-d3a7-4090-a303-af1133e504b9.mov

Please, share your db. I overloaded the tests and it still works

**Comment by hrosenbrock** [comment]
---

database-plugin: basic

---

```yaml:dbfolder
name:Schedule
description: The hardware schedule for the ... program.
columns:
  wbs:
    input: text
    key: wbs
    accessorKey: wbs
    label: WBS
    position: 1
    skipPersist: false
    isHidden: false
    sortIndex: -1
    config:
      enable_media_view: true
      media_width: 100
      media_height: 100
      isInline: false
      content_alignment: text-align-left
  __file__:
    key: __file__
    id: __file__
    input: markdown
    label: File
    accessorKey: __file__
    isMetadata: true
    skipPersist: false
    isDragDisabled: false
    csvCandidate: true
    position: 2
    isHidden: true
    sortIndex: -1
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: true
      task_hide_completed: true
  start_date:
    input: calendar
    accessorKey: start_date
    key: start_date
    id: start_date
    label: Start (Entered)
    position: 4
    skipPersist: false
    isHidden: false
    sortIndex: -1
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
  finish_date:
    input: calendar
    accessorKey: finish_date
    key: finish_date
    id: finish_date
    label: Finish (Entered)
    position: 5
    skipPersist: false
    isHidden: false
    sortIndex: -1
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
  start:
    input: formula
    accessorKey: start
    key: start
    id: start
    label: Start
    position: 6
    skipPersist: false
    isHidden: false
    sortIndex: -1
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
      content_alignment: text-align-center
      persist_formula: true
      formula_query: "${db.dataview.pages( '\"' + db.dataview.page(row.__file__).file.folder + '\"', db.dataview.page(row.__file__).file.path).where( x => (new String(x.wbs)).startsWith( row.wbs ) ).filter( x => x.start_date != undefined ).map( x => x.start_date.toFormat('y-MM-dd') ).sort().array()?.first() || ''}"
  finish:
    input: formula
    accessorKey: finish
    key: finish
    id: finish
    label: Finish
    position: 7
    skipPersist: false
    isHidden: false
    sortIndex: -1
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
      content_alignment: text-align-center
      persist_formula: true
      formula_query: "${db.dataview.pages( '\"' + db.dataview.page(row.__file__).file.folder + '\"', db.dataview.page(row.__file__).file.path).where( x => (new String(x.wbs)).startsWith( row.wbs ) ).filter( x => x.finish_date != undefined ).map( x => x.finish_date.toFormat('y-MM-dd') ).sort().array()?.last() || ''}"
  Status:
    input: select
    accessorKey: Status
    key: Status
    id: Status
    label: Status
    position: 8
    skipPersist: false
    isHidden: false
    sortIndex: -1
    options:
      - { label: "Not Started", backgroundColor: "hsl(139,16%,80%)"}
      - { label: "In Progress", backgroundColor: "hsl(228,68%,77%)"}
      - { label: "Complete", backgroundColor: "hsl(119,38%,67%)"}
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
  Task_Name:
    input: formula
    accessorKey: Task_Name
    key: Task_Name
    id: Task_Name
    label: Task Name
    position: 3
    skipPersist: false
    isHidden: false
    sortIndex: -1
    width: 472
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
      formula_query: ${row.__file__}
config:
  remove_field_when_delete_column: false
  cell_size: normal
  sticky_first_column: false
  group_folder_column: 
  remove_empty_folders: false
  automatically_group_files: false
  hoist_files_with_empty_attributes: true
  show_metadata_created: false
  show_metadata_modified: false
  show_metadata_tasks: false
  show_metadata_inlinks: false
  show_metadata_outlinks: false
  source_data: current_folder
  source_form_result: root
  source_destination_path: /
  frontmatter_quote_wrap: false
  row_templates_folder: /
  current_row_template: 
  pagination_size: 200
  enable_js_formulas: true
  formula_folder_path: functions
  inline_default: false
  inline_new_position: top
  date_format: yyyy-MM-dd
  datetime_format: "yyyy-MM-dd HH:mm:ss"
filters:
  enabled: false
  conditions:
```
