### ISSUE TITLE
Handle error problem with react version

### ISSUE THREAD

**Issue by Stilts15ak** [RafaelGB/obsidian-db-folder#626]
Getting this error: 
"Error parsing yaml
exception: TypeError: Cannot create property 'Input' on boolean 'false'"

I was trying to input a formula and it did not work, then the database disappeared. When into the .md file to erase the problem formula (which has worked before). However, it did not work and the database would not restore. Went ahead and deleted section with the problem column property, however got the above error.

Console logs and database .md file attached.

[obsidian.md-1669237482759.log](https://github.com/RafaelGB/obsidian-db-folder/files/10079176/obsidian.md-1669237482759.log)
[TV Show Status Database.md](https://github.com/RafaelGB/obsidian-db-folder/files/10079207/TV.Show.Status.Database.md)

**Comment by RafaelGB** [comment]
Hello @Stilts15ak , I tested your .md and was a problem with the error handler

In any case, the problem was the parse of the yaml. I don't know in which part yet (a really big yaml)

**Comment by RafaelGB** [comment]
When you edited the md file looks like you remove the config: flag
```yaml
config:
  remove_field_when_delete_column: false
  cell_size: normal
  sticky_first_column: true
  group_folder_column: 
  show_metadata_created: true
  show_metadata_modified: true
  show_metadata_tasks: false
  source_data: tag
  source_form_result: tv/tv-gen/tv_show
  frontmatter_quote_wrap: false
  row_templates_folder: Assets/Obsidian Templates
  current_row_template: Assets/Obsidian Templates/TV Show Status Template (Automated).md
  pagination_size: 10
  source_destination_path: TV SERIES DATABASE/TV SHOW STATUS
  show_metadata_inlinks: false
  show_metadata_outlinks: false
  formula_folder_path: /
  inline_default: false
  inline_new_position: top
  date_format: yyyy-MM-dd
  datetime_format: "yyyy-MM-dd HH:mm:ss"
  remove_empty_folders: false
  automatically_group_files: false
  hoist_files_with_empty_attributes: true
  enable_js_formulas: false
```

And the options are interpreted as another columns
