### ISSUE TITLE
[Bug]: empty space at the bottom when filter bar is hidden

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#654]
### What happened?

When enabling the `filter bar`, the database fills all the pane's height, but when disabling the `filter bar` there is an empty space not filled by the database. Can you make it fill all the pane height, even if the `filter bar` is hidden?

https://user-images.githubusercontent.com/38974541/206566371-3c059756-658b-4a5f-875a-ae91fba0ae08.mov

### What platform were you using?

Desktop

### Version of the plugin

3.0.1

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
the window has a 92% - 8% to support mobile pagination. We cN try to improve the design for sure

**Comment by RafaelGB** [comment]
I have to maintain that empty space in order to support the footer menus, but the % of scroll content will be adjusted in function of the resolution of your monitor now

```css
.database-plugin__scroll-container {
  will-change: transform;
  width: 100%;
  height: 98%;
  scroll-margin-bottom: 1rem;
}

@media only screen and (max-height: 1440px) {
  .database-plugin__scroll-container {
    will-change: transform;
    width: 100%;
    height: 95%;
  }
}

@media only screen and (max-height: 1024px) {
  .database-plugin__scroll-container {
    will-change: transform;
    width: 100%;
    height: 92%;
  }
}

@media only screen and (max-height: 768px) {
  .database-plugin__scroll-container {
    will-change: transform;
    width: 100%;
    height: 85%;
  }
}
```
