### ISSUE TITLE
[Bug]: Font color in category picker barely visible

### ISSUE THREAD

**Issue by jorgb** [RafaelGB/obsidian-db-folder#684]
### Contact Details

jorgdroid@gmail.com

### What happened?

I just updated to your latest version 3.1.0, and the font color of the items that I can select turned to white / light grey and are barely readable. I tried with the Things theme and Minimal theme. I am using a dark theme by default.

![image](https://user-images.githubusercontent.com/3519707/208862672-ac0b3270-5efa-4b47-a7a5-c7079727b3e8.png)

With regards,
- Jorgen

### What platform were you using?

Desktop

### Version of the plugin

3.1.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
oh! my bad. I will support the css themes with var(--text-normal) for the next version.

Thanks for the report!

**Comment by jorgb** [comment]
No problem, thank you for this great plugin.

**Comment by RafaelGB** [comment]
What theme are you using? With default & minimal does not happen

**Comment by pyrochlore** [comment]
Thanks for the great plugin.
I use default theme and also found the same problem.
![image](https://user-images.githubusercontent.com/3617615/209062123-16561fed-5744-4c3e-b323-f0d42ddf2845.png)

**Comment by jorgb** [comment]
It happens on the latest insider build, default theme (as stated) minimal theme as well. I did not tweak any CSS settings myself. Here is a dump of the options column, not sure if it helps;

```
type:
    input: tags
    accessorKey: type
    key: type
    id: type
    label: type
    position: 4
    skipPersist: false
    isHidden: false
    sortIndex: -1
    width: 251
    options:
      - { label: "cartoon", backgroundColor: "hsl(70, 95%, 90%)"}
      - { label: "painting", backgroundColor: "hsl(248, 95%, 90%)"}
      - { label: "waterverf", backgroundColor: "hsl(28, 95%, 90%)"}
      - { label: "sketch", backgroundColor: "hsl(269, 95%, 90%)"}
      - { label: "digital", backgroundColor: "hsl(10, 95%, 90%)"}
      - { label: "architecture", backgroundColor: "hsl(314, 95%, 90%)"}
      - { label: "scenery", backgroundColor: "hsl(159, 95%, 90%)"}
      - { label: "pen&ink", backgroundColor: "hsl(208, 95%, 90%)"}
      - { label: "figure", backgroundColor: "hsl(235, 95%, 90%)"}
      - { label: "vehicle", backgroundColor: "hsl(122,96%,90%)"}
      - { label: "portrait", backgroundColor: "hsl(178, 95%, 90%)"}
      - { label: "animal", backgroundColor: "hsl(35, 95%, 90%)"}
```
