### ISSUE TITLE
[Bug]: Pagination buttons are inaccessible in mobile.

### ISSUE THREAD

**Issue by uroybd** [RafaelGB/obsidian-db-folder#688]
### Contact Details

connect@utsob.me

### What happened?

Notice the pagination buttons at the bottom. They are hidden behind the bottom menu of Obsidian.

![Screenshot_2022-12-23-22-01-28-885_md obsidian](https://user-images.githubusercontent.com/4207230/209364501-b589b62b-5fb9-4d1e-8cba-eb75beca66ae.jpg)

### What platform were you using?

Mobile

### Version of the plugin

3.1.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
we have to support more kind of resolutions, thanks for the report !

**Comment by RafaelGB** [comment]
You can create your own css snippet to support your resolution

I do not know the exact dimensions of your device so maybe you have to test some values like max height pixels or height percentage

This is my bet to fix it

```css
@media only screen and (max-height: 768px) {
  .database-plugin__scroll-container {
    will-change: transform;
    width: 100%;
    height: 82%;
  }
}
```

**Comment by uroybd** [comment]
> You can create your own css snippet to support your resolution
> 
> I do not know the exact dimensions of your device so maybe you have to test some values like max height pixels or height percentage
> 
> This is my bet to fix it
> 
> ```css
> @media only screen and (max-height: 768px) {
>   .database-plugin__scroll-container {
>     will-change: transform;
>     width: 100%;
>     height: 82%;
>   }
> }
> ```

I tried this. Didn't help since the pagination button is positioned absolutely at the bottom. Instead, it worked:

```css
.database-plugin__pagination {
    width: fit-content;
    height: 40px;
    list-style: none;
    /* bottom: 1em; */
    /* position: absolute; */
    /* right: 0; */
    /* margin: 0; */
    padding: 0 10px 0 0;
    display: flex;
    column-gap: 2px;
    margin-top: 1em;
    margin-left: auto;
}
```

A good thing about this approach is it will work in all breakpoints. Even in situations like this on a desktop where the status bar overlaps the pagination buttons:

<img width="759" alt="Screenshot 2022-12-27 at 12 18 29 PM" src="https://user-images.githubusercontent.com/4207230/209620696-004099c2-fc50-4b81-aa4f-d618cc099295.png">
