### ISSUE TITLE
[Bug]: last row white space too big on display resolution (1360x768)

### ISSUE THREAD

**Issue by imeed166** [RafaelGB/obsidian-db-folder#700]
### What happened?

I'm using an old monitor with this resolution (1360x768). The white space becomes bigger when I put the obsidian app into the monitor. Could you please support this type of resolution, thank you.

https://user-images.githubusercontent.com/38974541/209556556-c1259a0c-61fa-4fd4-bb4b-a3889b751e63.mp4

### What platform were you using?

Desktop

### Version of the plugin

3.1.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
sure. Could you try a CSS snippet with this content?

```css
@media only screen and (max-height: 768px) {
  .database-plugin__scroll-container {
    will-change: transform;
    width: 100%;
    height: 92%;
  }
}
```

Currently this @media is necessary for mobile resolutions. Actual state
```css
@media only screen and (max-height: 768px) {
  .database-plugin__scroll-container {
    will-change: transform;
    width: 100%;
    height: 85%;
  }
}
```
