### ISSUE TITLE
[VS] Remove margins inside cells <p> added with obsidian markdown renderer

### ISSUE THREAD

**Issue by RafaelGB** [RafaelGB/obsidian-db-folder#71]

**Comment by RafaelGB** [comment]
@artisticat1  mentions to fix with
```css
.data-input p { margin: initial; } should work
```
