### ISSUE TITLE
[Bug]: DB Folder Saving to frontmatter even if persisting is off.

### ISSUE THREAD

**Issue by uroybd** [RafaelGB/obsidian-db-folder#738]
### Contact Details

roy@utsob.me

### What happened?

DB Folder Saving to frontmatter even if persisting is off. It costed me tremendous amount of time to get my data back to the previous version.

### What platform were you using?

Cross

### Version of the plugin

3.2.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by RafaelGB** [comment]
Hello @uroybd ,

could you share an example?
I don't know what you mean here

Sound like an important problem to you and it will be treated with priority once the case is understood

**Comment by uroybd** [comment]
![Screenshot_2023-01-07-18-17-36-637_md obsidian](https://user-images.githubusercontent.com/4207230/211150681-97841cbb-3980-4417-aefa-6863e09630de.jpg)

Notice the persist formula is off.

Then comes some errors:

![Screenshot_2023-01-07-18-17-03-394_md obsidian](https://user-images.githubusercontent.com/4207230/211150729-4b202234-968a-40b5-8dc0-74ef98d7591d.jpg)

And then this:

![Screenshot_2023-01-07-18-28-39-436_md obsidian](https://user-images.githubusercontent.com/4207230/211150750-4a6bf74f-ee1d-4c5f-b280-967bcea031de.jpg)

In phone, the notes are intact. However, in desktop the content changes too.

**Comment by RafaelGB** [comment]
oh I see

Could you share your script? I will test it as soon as I can

**Comment by uroybd** [comment]
> oh I see
> 
> Could you share your script? I will test it as soon as I can

The index:

```yaml:dbfolder
name: Journal
description: 
columns:
  __file__:
    key: __file__
    id: __file__
    input: markdown
    label: File
    accessorKey: __file__
    isMetadata: true
    skipPersist: false
    isDragDisabled: false
    csvCandidate: true
    position: 4
    isHidden: true
    sortIndex: -1
    width: 230.27273559570312
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: true
      task_hide_completed: true
      footer_type: none
  title:
    input: formula
    accessorKey: title
    key: title
    id: title
    label: title
    position: 1
    skipPersist: false
    isHidden: false
    sortIndex: -1
    width: 304.2735137939453
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
      footer_type: none
      content_alignment: text-align-left
      wrap_content: true
      formula_query: ${db.js.formatters().format_title_link(row, '__file__')}
  tags:
    input: tags
    accessorKey: tags
    key: tags
    id: tags
    label: tags
    position: 3
    skipPersist: false
    isHidden: false
    sortIndex: -1
    width: 242.27273559570312
    options:
      - { label: "thoughts", backgroundColor: "hsl(225, 95%, 90%)"}
      - { label: "philosophy", backgroundColor: "hsl(308, 95%, 90%)"}
      - { label: "credential", backgroundColor: "hsl(187, 95%, 90%)"}
      - { label: "novel", backgroundColor: "hsl(305, 95%, 90%)"}
      - { label: "physiology", backgroundColor: "hsl(10, 95%, 90%)"}
      - { label: "autobiography", backgroundColor: "hsl(124, 95%, 90%)"}
      - { label: "buddhism", backgroundColor: "hsl(179, 95%, 90%)"}
      - { label: "travelog", backgroundColor: "hsl(216, 95%, 90%)"}
      - { label: "bookreview", backgroundColor: "hsl(279, 95%, 90%)"}
      - { label: "পাঠপ্রতিক্রিয়া", backgroundColor: "hsl(117, 95%, 90%)"}
      - { label: "short story", backgroundColor: "hsl(198, 95%, 90%)"}
      - { label: "art", backgroundColor: "hsl(207, 95%, 90%)"}
      - { label: "job", backgroundColor: "hsl(304, 95%, 90%)"}
      - { label: "passion", backgroundColor: "hsl(168, 95%, 90%)"}
      - { label: "programming", backgroundColor: "hsl(293, 95%, 90%)"}
      - { label: "spirituality", backgroundColor: "hsl(156, 95%, 90%)"}
      - { label: "beliefs", backgroundColor: "hsl(24, 95%, 90%)"}
      - { label: "society", backgroundColor: "hsl(47, 95%, 90%)"}
      - { label: "clichébuster", backgroundColor: "hsl(67, 95%, 90%)"}
      - { label: "historical", backgroundColor: "hsl(323, 95%, 90%)"}
      - { label: "bengali", backgroundColor: "hsl(2, 95%, 90%)"}
      - { label: "modern", backgroundColor: "hsl(197, 95%, 90%)"}
      - { label: "western", backgroundColor: "hsl(331, 95%, 90%)"}
      - { label: "scripture", backgroundColor: "hsl(184, 95%, 90%)"}
      - { label: "classic", backgroundColor: "hsl(354, 95%, 90%)"}
      - { label: "letters", backgroundColor: "hsl(326, 95%, 90%)"}
      - { label: "anthropology", backgroundColor: "hsl(165, 95%, 90%)"}
      - { label: "american", backgroundColor: "hsl(112, 95%, 90%)"}
      - { label: "european", backgroundColor: "hsl(157, 95%, 90%)"}
      - { label: "life", backgroundColor: "hsl(256, 95%, 90%)"}
      - { label: "প্রেম", backgroundColor: "hsl(312, 95%, 90%)"}
      - { label: "বিষাদ", backgroundColor: "hsl(352, 95%, 90%)"}
      - { label: "nihilism", backgroundColor: "hsl(243, 95%, 90%)"}
      - { label: "work", backgroundColor: "hsl(263, 95%, 90%)"}
      - { label: "science", backgroundColor: "hsl(106, 95%, 90%)"}
      - { label: "frustration", backgroundColor: "hsl(28, 95%, 90%)"}
      - { label: "poem", backgroundColor: "hsl(123, 95%, 90%)"}
      - { label: "কবিতা", backgroundColor: "hsl(178, 95%, 90%)"}
      - { label: "খসড়া", backgroundColor: "hsl(224, 95%, 90%)"}
      - { label: "বৃষ্টি", backgroundColor: "hsl(272, 95%, 90%)"}
      - { label: "ভ্রমণ", backgroundColor: "hsl(111, 95%, 90%)"}
      - { label: "ai", backgroundColor: "hsl(186, 95%, 90%)"}
      - { label: "consciousness", backgroundColor: "hsl(84, 95%, 90%)"}
      - { label: "ethics", backgroundColor: "hsl(40, 95%, 90%)"}
      - { label: "rights", backgroundColor: "hsl(128, 95%, 90%)"}
      - { label: "politics", backgroundColor: "hsl(240, 95%, 90%)"}
      - { label: "contemplation", backgroundColor: "hsl(281, 95%, 90%)"}
      - { label: "অপলাপ", backgroundColor: "hsl(18, 95%, 90%)"}
      - { label: "গদ্য", backgroundColor: "hsl(92, 95%, 90%)"}
      - { label: "বাবা", backgroundColor: "hsl(198, 95%, 90%)"}
      - { label: "স্মৃতি", backgroundColor: "hsl(246, 95%, 90%)"}
      - { label: "দুঃখ", backgroundColor: "hsl(333, 95%, 90%)"}
      - { label: "alcoholic", backgroundColor: "hsl(330, 95%, 90%)"}
      - { label: "reflections", backgroundColor: "hsl(265, 95%, 90%)"}
      - { label: "সুখ", backgroundColor: "hsl(281, 95%, 90%)"}
      - { label: "corona20", backgroundColor: "hsl(259, 95%, 90%)"}
      - { label: "despair", backgroundColor: "hsl(355, 95%, 90%)"}
      - { label: "love", backgroundColor: "hsl(74, 95%, 90%)"}
      - { label: "summer", backgroundColor: "hsl(101, 95%, 90%)"}
      - { label: "death", backgroundColor: "hsl(136, 95%, 90%)"}
      - { label: "pressure", backgroundColor: "hsl(111, 95%, 90%)"}
      - { label: "mono-no-aware", backgroundColor: "hsl(331, 95%, 90%)"}
      - { label: "childhood", backgroundColor: "hsl(70, 95%, 90%)"}
      - { label: "sociology", backgroundColor: "hsl(104, 95%, 90%)"}
      - { label: "religion", backgroundColor: "hsl(332, 95%, 90%)"}
      - { label: "poetry", backgroundColor: "hsl(217, 95%, 90%)"}
      - { label: "literature", backgroundColor: "hsl(298, 95%, 90%)"}
      - { label: "year-end", backgroundColor: "hsl(88, 95%, 90%)"}
      - { label: "tedium", backgroundColor: "hsl(316, 95%, 90%)"}
      - { label: "tiredness", backgroundColor: "hsl(68, 95%, 90%)"}
      - { label: "myth", backgroundColor: "hsl(57, 95%, 90%)"}
      - { label: "zen", backgroundColor: "hsl(18, 95%, 90%)"}
      - { label: "city", backgroundColor: "hsl(154, 95%, 90%)"}
      - { label: "khulna", backgroundColor: "hsl(323, 95%, 90%)"}
      - { label: "melancholy", backgroundColor: "hsl(149, 95%, 90%)"}
      - { label: "memories", backgroundColor: "hsl(19, 95%, 90%)"}
      - { label: "christmas", backgroundColor: "hsl(220, 95%, 90%)"}
      - { label: "crisis", backgroundColor: "hsl(290, 95%, 90%)"}
      - { label: "procrastination", backgroundColor: "hsl(280, 95%, 90%)"}
      - { label: "self-reflection", backgroundColor: "hsl(267, 95%, 90%)"}
      - { label: "ego", backgroundColor: "hsl(156, 95%, 90%)"}
      - { label: "reading", backgroundColor: "hsl(103, 95%, 90%)"}
      - { label: "year in books", backgroundColor: "hsl(28, 95%, 90%)"}
      - { label: "closing note", backgroundColor: "hsl(325, 95%, 90%)"}
      - { label: "being", backgroundColor: "hsl(292, 95%, 90%)"}
      - { label: "depression", backgroundColor: "hsl(248, 95%, 90%)"}
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
      footer_type: none
  mood:
    input: formula
    accessorKey: mood
    key: mood
    id: mood
    label: mood
    position: 5
    skipPersist: false
    isHidden: false
    sortIndex: -1
    width: 88
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
      footer_type: none
      content_alignment: text-align-center
      formula_query: ${db.js.formatters().format_mood(row.mood)}
  weather:
    input: formula
    accessorKey: weather
    key: weather
    id: weather
    label: weather
    position: 6
    skipPersist: false
    isHidden: false
    sortIndex: -1
    width: 77
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
      footer_type: none
      formula_query: ${db.js.formatters().format_weather(row.weather)}
      content_alignment: text-align-center
  created:
    input: formula
    accessorKey: created
    key: created
    id: created
    label: created
    position: 7
    skipPersist: false
    isHidden: false
    sortIndex: 1
    width: 151.63638305664062
    isSorted: true
    isSortedDesc: true
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
      footer_type: none
      formula_query: ${db.js.formatters().format_compact_date(row.created)}
  location:
    input: text
    accessorKey: location
    key: location
    id: location
    label: location
    position: 2
    skipPersist: false
    isHidden: false
    sortIndex: -1
    width: 191
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
      footer_type: none
      wrap_content: true
      content_alignment: text-align-left
  updated:
    input: formula
    accessorKey: updated
    key: updated
    id: updated
    label: updated
    position: 100
    skipPersist: false
    isHidden: false
    sortIndex: -1
    width: 141
    config:
      enable_media_view: true
      link_alias_enabled: true
      media_width: 100
      media_height: 100
      isInline: false
      task_hide_completed: true
      footer_type: none
      formula_query: ${db.js.formatters().format_compact_date(row.updated)}
config:
  remove_field_when_delete_column: false
  cell_size: normal
  sticky_first_column: false
  group_folder_column: 
  remove_empty_folders: false
  automatically_group_files: false
  hoist_files_with_empty_attributes: true
  show_metadata_created: false
  show_metadata_modified: false
  show_metadata_tasks: false
  show_metadata_inlinks: false
  show_metadata_outlinks: false
  source_data: current_folder
  source_form_result: root
  source_destination_path: /
  frontmatter_quote_wrap: false
  row_templates_folder: /
  current_row_template: 
  pagination_size: 25
  enable_js_formulas: true
  formula_folder_path: js
  inline_default: false
  inline_new_position: top
  date_format: yyyy-MM-dd
  datetime_format: "yyyy-MM-dd'T'HH:mm:ssZZ"
  enable_footer: false
  font_size: 16
  metadata_date_format: "yyyy-MM-dd HH:mm:ss"
filters:
  enabled: false
  conditions:
```
