### ISSUE TITLE
[Bug]: Enumerations with wikilinks are not affected by font size

### ISSUE THREAD

**Issue by ManuelVicenteG** [RafaelGB/obsidian-db-folder#975]
### Contact Details

manuel.vicente.ga@gmail.com

### What happened?

Enumerations with wikilinks are not affected by the font size of the settings.
For example,
![imagen](https://github.com/RafaelGB/obsidian-db-folder/assets/123266716/3555e9c1-5cce-4b13-8b8e-cf5d607a9e87)
Appears as
![imagen](https://github.com/RafaelGB/obsidian-db-folder/assets/123266716/258faaaa-840e-4662-85b5-103eb2eed2e4)
With a larger font size than the one defined in the settings and that actually appears in the other columns

### What platform were you using?

Desktop

### Version of the plugin

3.5.0

### Are you using the latest version of the plugin in your Obsidian vault?

- [X] I have verified that I am on the latest version

### Are you check if there is a similar issue?

- [X] I have verified that there are not similar issues

**Comment by shadowmaru** [comment]
I have a similar issue. I've tracked down to the element that changes the font size. It is applied to `<p>` elements, but not for `<li>`.

```css
.database-plugin__td.data-input p {
    margin: 0;
    font-size: var(--dbfolder-font-size);
}
```

For lists, it inherits this rule:
```css
.data-input * {
    margin: initial;
}
```

I don't know if the best solution would be copying the same rule to `<li>` elements, or wrapping the content of list items in a `<p>`.
